type State = {
  code: string;
  name: string;
  taxMode?: string;
  borderTax: number;
};

type BORDES = {
  [key: string]: string[];
};

export const taxModes = [
  { value: "daily", label: "Daily" },
];

export const states: State[] = [
  { code: 'UP', name: 'Uttar Pradesh', borderTax: 150 },
  { code: 'RJ', name: 'Rajasthan', borderTax: 190 },
  { code: 'HR', name: 'Haryana', borderTax: 130 },
  { code: 'PB', name: 'Punjab', borderTax: 270 },
  { code: 'UK', name: 'Uttarakhand', borderTax: 280 },
  { code: 'HP', name: 'Himachal Pradesh', borderTax: 260 },
  { code: 'MP', name: 'Madhya Pradesh', borderTax: 255 },
  { code: 'GJ', name: 'Gujarat', borderTax: 0 },
  { code: 'CG', name: 'Chhattisgarh', borderTax: 0 },
  { code: 'BR', name: 'Bihar', borderTax: 0 },
  { code: 'JK', name: 'Jharkhand', borderTax: 0 },
  { code: 'MH', name: 'Maharashtra', borderTax: 850 }
];

export const borders: BORDES = {
  UP: [
    "Ghazipur",
    "Ghaziabad",
    "Mathura",
    "Pilibhit",
    "Agra",
    "Aligarh",
    "Baghpat",
    "Ballia",
    "Balrampur",
    "Banda",
    "Bareilly",
    "Bijnor",
    "Chanduali",
    "Chitrakoot",
    "Deoria",
    "Etawah",
    "Gautam Buddh Nagar",
    "Hamirpur",
    "Jhansi",
    "Khushi Nagar",
    "Lakhimpur",
    "Maharganj",
    "Mahoba",
    "Mirzapur",
    "Muzzafarnagar",
    "Orai",
    "Prayagraj",
    "Rampur",
    "Saharanpur",
    "Shamli",
    "Shrabasti",
    "Siddharth Nagar",
    "Sonbhadra"
  ],
  RJ: [
    "Alwar",
    "Jaipur",
    "Banswara",
    "Baran",
    "bharatpur",
    "Chittorgarh",
    "Churu",
    "Dholpur",
    "Dungarpur",
    "Ganganagar",
    "Hanumangarh",
    "Jalor",
    "Jhalawar",
    "Jhunjhunun",
    "pratapgarh",
    "Pali",
    "Sirohi",
  ],
  HR: [
    "Gurgaon",
    "Ambala",
    "Nuh",
    "Faridabad",
    "Bhiwani",
    "Chrakhi Dadri",
    "Fatehabad",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "palwal",
    "panchkula",
    "panipat",
    "rewari",
    "sirsa",
    "sonipat",
    "yammuna nagar",
  ],
  PB: [
    "Mohali",
    "Fazilka",
    "Bhatinda",
    "Muktsar",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sangrur",
  ],
  UK: [
    "Deharadun",
    "Haridwar",
    "Kotdwar",
    "Udham singh nagar",
  ],
  HP: [
    "parwanoo",
    "baddi",
    "barotiwala",
    "damtal",
    "kalaamb",
    "kandwal",
    "methapur",
    "Paonta sahib",
    "Swargaht",
    "Tipra",
    "Tunnuhatti"
  ],
  MP: [
    "Agar Malwa",
    "Alirajpur",
    "Anuppur",
  ],
  GJ: [
    "Shamlaji",
    "Ambaji",
    "Amirgarh",
    "Bhilad",
    "Chhota Udepur",
    "Dahod",
    "Gundari",
    "Hazira",
    "Jamnagar",
    "Kaprada",
    "Sagbara",
    "Samkhiyali",
    "Sonagadh",
    "Tharad (Khoda)",
    "Thavar",
    "Waghai",
    "Zalod",
  ],
  CG: [
    "Ambikapur RTO",
    "Baikuthpur DTO",
    "Baloda Bazar DTO"
  ],
  BR: [
    "Araia",
    "Patna",
    "Arawal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bettiah",
    "Bhagalpur",
    "Buxar",
    "Bhojpur",
    "Buxur",
    "Chpara",
    "Darbhanga",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanbad",
    "Katighar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Motihari",
    "Munger",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Purnea",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Siwan",
    "Supaul",
    "vaishali",
  ],
  JK: [
    "Dhanbad",
    "Bokaro",
    "Chatra",
    "Deoghar",
    "Dumka",
    "East Singhbhum (Jamshedpur)",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribagh",
    "Jamtara",
    "Khunti",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Palamu",
    "Ramgarh",
    "Ranchi",
    "Sahibganj",
    "Saraikela",
    "Simdega",
    "West Singhbhum (Chaibasa)",
  ],
  MH: [
    "Aurangabad",
    "Ahmed Nagar",
    "Akluj",
    "Ankola",
    "Ambejogai",
    "Amrawati",
    "Baramati",
    "Beed",
    "Bhandara",
    "Borivali",
    "Bhuldhana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondhia",
    "Hingoli",
    "Jalna",
    "Jalgaon",
    "Kalyan",
    "Karad",
    "Kolhapur",
    "Latur",
    "Malegaon",
    "Mumbai (central)",
    "Mumbai (East)",
    "Mumbai (West)",
    "Nagpur (East)",
    "Nagpur (West)",
    "Nagpur (Rural)",
    "Nanded",
    "Nashik",
    "Osmanabad",
    "Panvel",
    "Parbhani",
    "Pen (Raibad)",
    "Pimri Chichwad",
    "Pune",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg (Kudal)",
    "Solapur",
    "Srirampur",
    "Thane",
    "Vasai/New Mumbai",
    "Wardha",
    "Washim",
    "Yawatmal",
  ],
}